### ISSUE TITLE
! LaTeX Error: Environment CSLReferences undefined.

### ISSUE THREAD

**Issue by DajaCosmosInACell** [nkurzaw/heididown#5]
Hi Nils,

thanks so much for providing this!

Unfortunately I ran into an error when trying to knit:

```
! LaTeX Error: Environment CSLReferences undefined.

Error: LaTeX failed to compile thesis.tex.
```

If I understand correctly, the same error is described here and a solution is suggested:
https://stackoverflow.com/a/67244130

Unfortunately I don't understand where this needs to be added (I did not find a similar looking section to replace in template.tex).
Maybe you have an idea?

Cheers,
Daja

[thesis.log](https://github.com/nkurzaw/heididown/files/9167252/thesis.log)

**Comment by nkurzaw** [comment]
Hi Daja, 
you're welcome :) I'm happy people find it useful!

I had a quick look and didn't find where to fix it either. 
Just a question: did you change the 5th line in the template.tex file `\usepackage[authoryear]{natbib}  ` to use a different citation style?

Cheers,
Nils

**Comment by DajaCosmosInACell** [comment]
Thanks for taking a look!

No, I made no changes, just tried a test-knit directly after initial setup (as described in the readme).

**Comment by nkurzaw** [comment]
Ok, that's good to know!

**Comment by nkurzaw** [comment]
Did you try reinstalling/updating the rmarkdown package yet?
According to this: https://github.com/rstudio/rmarkdown/issues/1649
The problem should be fixed since late 2019

**Comment by DajaCosmosInACell** [comment]
Updating rmarkdown did not fix the error.

As suggested further down in the thread you linked, I then tried deinstalling pandocs (as specified here: https://pandoc.org/installing.html, which is also where I downloaded it from earlier). 

Now it works! Thank you for your help!! :)

**Comment by nkurzaw** [comment]
Perfect :) !! All the best for the writing!
